doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      datetime_functions:
        date: DoctrineExtensions\Query\Mysql\Date
        dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
        month: DoctrineExtensions\Query\Mysql\Month
        year: DoctrineExtensions\Query\Mysql\Year
      numeric_functions:
        power: DoctrineExtensions\Query\Mysql\Power
      string_functions:
        group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
