fos_rest:
  param_fetcher_listener: true
  allowed_methods_listener: true
  routing_loader: false
  versioning: true
  view:
    formats:
      json: true
    view_response_listener:  true
  format_listener:
    rules:
      - { path: ^/api/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
  zone:
    - { path: ^/api/ }
