fos_rest:
  allowed_methods_listener: true
  body_listener:
    enabled: true
    default_format: json
  format_listener:
    rules:
      - { path: ^/api/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  param_fetcher_listener: true
  serializer:
    serialize_null: true
  versioning: true
  view:
    formats:
      json: true
    view_response_listener:  true
  zone:
    - { path: ^/api/ }
