# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
  configs:
    forum_post_reply:
      enableContextMenu: false
      toolbar: 'forum_post_reply_toolbar'
      uiColor: '#1D679F'
      language: 'nl'
  toolbars:
    configs:
      forum_post_reply_toolbar: [ "@styles", "@links", "@paragraph", "@clipboard", "@tools"]
    items:
      styles: ['Bold', 'Italic', 'Strike', 'HorizontalRule', '-', 'RemoveFormat']
      links: ['Link', 'Unlink']
      clipboard: ['Cut', 'Copy', 'Paste', 'PasteText', '-', 'Undo', 'Redo']
      paragraph: ['NumberedList', 'BulletedList', 'Blockquote']
      tools: ['Maximize', 'SpecialChar', 'Smiley']
