framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: true
  validation: { enable_annotations: true }

  session:
    enabled: true
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    cookie_secure: true
    cookie_samesite: strict
    cookie_lifetime: 8640000
    use_cookies: true

  php_errors:
    log: true
