framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: true
  validation: { enable_annotations: true }

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax

  php_errors:
    log: true
