security:
  encoders:
    App\Entity\User:
      algorithm: auto
    Symfony\Component\Security\Core\User\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
    api_user_provider:
      memory:
        users:
          'nl.somda.somda.app': { password: '$argon2id$v=19$m=65536,t=4,p=1$79JQAdFwBv6M6e+C098Z+Q$l+L4HEmPpy3B8KRx9M2yEmrfORbgRU33IKiKaWDVOHI', roles: 'ROLE_API_USER' }
          'aar.claij.nl': { password: '$argon2id$v=19$m=65536,t=4,p=1$ek13WTRSQjBJRTYzVjdNcg$t7+BabVXHW/AiRrs/2F2h8NzCEMYwGzGyXnECkjmneY', roles: 'ROLE_API_USER' }
    all_users:
      chain:
        providers: ['api_user_provider', 'app_user_provider']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js|webfonts)/
      security: false
    api:
      anonymous: false
      http_basic:
        realm: Secured API
      json_login:
        check_path: api_authenticate
      lazy: true
      pattern: ^/api/
      provider: all_users
      stateless: true
    main:
      anonymous: true
      lazy: true
      stateless: true
      provider: app_user_provider
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: logout
        target: home
      remember_me:
        secret: '%env(APP_SECRET)%'
        httponly: true
        always_remember_me: true
        lifetime: 8640000
        secure: true
        samesite: null

  role_hierarchy:
    ROLE_ADMIN:
      - ROLE_USER
      - ROLE_ABBREVIATIONS
      - ROLE_PASSING_ROUTES
      - ROLE_ROUTE_OVERVIEW
      - ROLE_SPOTS_EDIT
      - ROLE_SPOTS_NEW
      - ROLE_SPOTS_RECENT
      - ROLE_TRAIN_DDAR
      - ROLE_TRAIN_NAMES
    ROLE_SUPER_ADMIN:
      - ROLE_ADMIN
      - ROLE_ADMIN_BANS
      - ROLE_ADMIN_NEWS
      - ROLE_ADMIN_RAIL_NEWS
      - ROLE_ADMIN_ROUTE_NUMBER_LIST
      - ROLE_ADMIN_SPECIAL_ROUTES
      - ROLE_ADMIN_TRAINTABLE_EDIT
      - ROLE_ADMIN_WIKI

  access_control:
    - { path: ^/inloggen, roles: IS_AUTHENTICATED_ANONYMOUSLY }
