api_documentation:
  path: /documentation/
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_authenticate:
  path: /{version}/authenticate/
  methods: [POST]
  controller: App\Controller\Api\SecurityController::loginAction
api_authenticate_token:
  path: /{version}/authenticate-token/{id}/{token}/
  methods: [GET]
  controller: App\Controller\Api\SecurityController::verifyAction

api_locations:
  path: /{version}/locations/
  methods: [GET]
  controller: App\Controller\Api\LocationController::indexAction
api_locations_search:
  path: /{version}/locations/{searchMethod}/{search}/
  methods: [GET]
  controller: App\Controller\Api\LocationController::indexAction

api_train_table_years:
  path: /{version}/train-table-years/
  methods: [GET]
  controller: App\Controller\Api\TrainTableYearController::indexAction

api_train_table:
  path: /{version}/train-table/
  methods: [GET]
  controller: App\Controller\Api\TrainTableController::indexAction

api_forum:
  path: /{version}/forum-forums/
  methods: [GET]
  controller: App\Controller\Api\ForumForumController::indexAction
api_forum_forum:
  path: /{version}/forum-discussions/{id}/
  methods: [GET]
  controller: App\Controller\Api\ForumForumController::forumAction

api_forum_discussion:
  path: /{version}/forum-discussion/{id}/
  methods: [GET]
  controller: App\Controller\Api\ForumDiscussionController::indexAction
api_forum_discussion_page:
  path: /{version}/forum-discussion/{id}/{pageNumber}/
  methods: [GET]
  requirements: { id: \d+, pageNumber: \d+ }
  controller: App\Controller\Api\ForumDiscussionController::indexAction
api_forum_discussion_post:
  path: /{version}/forum-discussion/{id}/p{postId}/
  methods: [GET]
  requirements: { id: \d+, postId: \d+ }
  controller: App\Controller\Api\ForumDiscussionController::indexAction

api_forum_discussion_post_reply:
  path: /{version}/forum-discussion/{discussionId}/reageren/
  methods: [POST]
  requirements: { discussionId: \d+ }
  controller: App\Controller\Api\ForumPostController::replyAction
