api:
  path: /dienstregeling/
  methods: [GET]
  controller: App\Controller\ApiController::trainTableAction
api_search:
  path: /dienstregeling/{trainTableYearId}/{routeNumber}/
  methods: [GET]
  requirements: { trainTableYearId: \d+ }
  controller: App\Controller\ApiController::trainTableAction
