api_documentation:
  path: /documentation/
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

###################
# User management #
###################
api_authenticate:
  path: /{version}/authenticate/
  methods: [POST]
  controller: App\Controller\Api\SecurityController::loginAction
api_authenticate_token:
  path: /{version}/authenticate-token/{id}/{token}/
  methods: [GET]
  controller: App\Controller\Api\SecurityController::verifyAction

########
# News #
########
api_news:
  path: /{version}/news/
  methods: [GET]
  controller: App\Controller\Api\NewsController::indexAction
api_news_text:
  path: /{version}/news/{id}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\Api\NewsController::indexAction
api_rail_news:
  path: /{version}/rail-news/
  methods: [GET]
  controller: App\Controller\Api\NewsController::railNewsAction

###############
# Information #
###############
api_locations:
  path: /{version}/locations/
  methods: [GET]
  controller: App\Controller\Api\LocationController::indexAction
api_locations_search:
  path: /{version}/locations/{searchMethod}/{search}/
  methods: [GET]
  controller: App\Controller\Api\LocationController::indexAction

###############
# Train table #
###############
api_train_table_years:
  path: /{version}/train-table-years/
  methods: [GET]
  controller: App\Controller\Api\TrainTableYearController::indexAction

api_train_table:
  path: /{version}/train-table/{trainTableYearId}/{routeNumber}/
  methods: [GET]
  requirements: { trainTableYearId: \d+, routeNumber: \d+ }
  controller: App\Controller\Api\TrainTableController::indexAction

api_passing_routes:
  path: /{version}/passing-routes/{trainTableYearId}/{locationName}/{dayNumber}/{startTime}/{endTime}/
  methods: [GET]
  requirements: { trainTableYearId: \d+, dayNumber: \d+ }
  controller: App\Controller\Api\TrainTableController::passingRoutesAction

api_route_overview:
  path: /{version}/route-overview/
  methods: [GET]
  controller: App\Controller\Api\TrainTableController::routeOverviewAction
api_route_overview_year:
  path: /{version}/route-overview/{trainTableYearId}/
  methods: [GET]
  requirements: { trainTableYearId: \d+ }
  controller: App\Controller\Api\TrainTableController::routeOverviewAction
api_route_overview_year_route_list:
  path: /{version}/route-overview/{trainTableYearId}/{routeListId}/
  methods: [GET]
  requirements: { trainTableYearId: \d+, routeListId: \d+ }
  controller: App\Controller\Api\TrainTableController::routeOverviewAction

#########
# Spots #
#########
api_spots:
  path: /{version}/spots/{maxMonths}/{searchParameters}
  methods: [GET]
  requirements: { maxMonths: '1|3|6|12|24|36|48|60|99', searchParameters: .+ }
  controller: App\Controller\Api\SpotController::indexAction

#########
# Forum #
#########
api_forum:
  path: /{version}/forum-forums/
  methods: [GET]
  controller: App\Controller\Api\ForumForumController::indexAction
api_forum_forum:
  path: /{version}/forum-discussions/{id}/
  methods: [GET]
  controller: App\Controller\Api\ForumForumController::forumAction

api_forum_discussion:
  path: /{version}/forum-discussion/{id}/
  methods: [GET]
  controller: App\Controller\Api\ForumDiscussionController::indexAction

api_forum_discussion_reply:
  path: /{version}/forum-discussion/{discussionId}/reply/
  methods: [POST]
  requirements: { discussionId: \d+ }
  controller: App\Controller\Api\ForumPostController::replyAction

api_forum_favorites:
  path: /{version}/forum-favorites/
  methods: [GET]
  controller: App\Controller\Api\ForumDiscussionController::favoritesAction

api_forum_unread:
  path: /{version}/forum-unread/
  methods: [GET]
  controller: App\Controller\Api\ForumDiscussionController::unreadAction

api_forum_search:
  path: /{version}/forum-search/{searchMethod}/{terms}/
  methods: [GET]
  requirements: { searchMethod: 'all|some' }
  controller: App\Controller\Api\ForumSearchController::indexAction

########
# User #
########
api_profile:
  path: /profile/
  methods: [GET]
  controller: App\Controller\Api\ProfileController::indexAction
api_profile_update:
  path: /profile/
  methods: [POST]
  controller: App\Controller\Api\ProfileController::updateAction
