api_documentation:
  path: /documentation/
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_train_table_years:
  path: /dienstregelingen/
  methods: [GET]
  controller: App\Controller\Api\TrainTableYearController::indexAction

api_train_table:
  path: /dienstregeling/
  methods: [GET]
  controller: App\Controller\Api\TrainTableController::indexAction
