mobile_home:
  path: /
  methods: [GET, POST]
  controller: App\Controller\MobileController::indexAction

###################
# User management #
###################
mobile_login:
  path: /inloggen/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::loginMobileAction
mobile_logout:
  path: /uitloggen/
  methods: [GET]
  controller: App\Controller\SecurityController::logoutMobileAction

###############
# Train table #
###############
mobile_train_table:
  path: /dienstregeling/
  methods: [GET]
  controller: App\Controller\MobileController::trainTableAction
mobile_train_table_search:
  path: /dienstregeling/{routeNumber}/
  methods: [GET]
  requirements: { routeNumber: \d+ }
  controller: App\Controller\MobileController::trainTableAction
mobile_passing_routes:
  path: /doorkomststaat/
  methods: [GET]
  controller: App\Controller\MobileController::passingRoutesAction
mobile_passing_routes_search:
  path: /doorkomststaat/{locationName}/{dayNumber}/{startTime}/{endTime}/
  methods: [GET]
  requirements: { dayNumber: \d+ }
  controller: App\Controller\MobileController::passingRoutesAction
mobile_special_routes:
  path: /drgl/
  methods: [GET]
  controller: App\Controller\MobileController:specialRoutesAction
mobile_special_route:
  path: /drgl/{id}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\MobileController:specialRoutesAction
