home:
  path: /
  methods: [GET]
  controller: App\Controller\HomeController::indexAction
home_update_layout_json:
  path: /layout-bewerken/{layout}/
  methods: [GET]
  controller: App\Controller\HomeLayoutController::updateAction

###################
# User management #
###################
login:
  path: /inloggen/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::loginAction
login_with_username:
  path: /inloggen/{username}/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::loginAction
logout:
  path: /uitloggen/
  methods: [GET]
  controller: App\Controller\SecurityController::logoutAction
register:
  path: /registreren/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::registerAction
activate:
  path: /activeren/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\SecurityController::activateAction
activate_with_key:
  path: /activeren/{id}/{key}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\SecurityController::activateAction
change_password:
  path: /wachtwoord-wijzigen/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::changePasswordAction
lost_password:
  path: /wachtwoord-vergeten/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::lostPasswordAction

################
# Home-screens #
################
information_home:
  path: /informatie/
  methods: [GET]
  controller: App\Controller\HomeController::indexAction
train_table_home:
  path: /dienstregelingen/
  methods: [GET]
  controller: App\Controller\HomeController::indexAction
somda_home:
  path: /somda/
  methods: [GET]
  controller: App\Controller\HomeController::indexAction

########
# News #
########
news:
  path: /nieuws/
  methods: [GET]
  controller: App\Controller\NewsController::indexAction
news_text:
  path: /nieuws/{id}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\NewsController::indexAction

###############
# Information #
###############
jargon:
  path: /jargon/
  methods: [GET]
  controller: App\Controller\InformationController::jargonAction
location:
  path: /verkortingen/
  methods: [GET]
  controller: App\Controller\InformationController:locationsAction
location_search:
  path: /verkortingen/{searchMethod}/{search}/
  methods: [GET]
  controller: App\Controller\InformationController:locationsAction
uic:
  path: /uic/
  methods: [GET]
  controller: App\Controller\InformationController:uicAction

###############
# Train table #
###############
train_table:
  path: /dienstregeling/
  methods: [GET]
  controller: App\Controller\TrainTableController:indexAction
train_table_search:
  path: /dienstregeling/{trainTableIndexNumber}/{routeNumber}/
  methods: [GET]
  requirements: { trainTableIndexNumber: \d+ }
  controller: App\Controller\TrainTableController:indexAction
passing_routes:
  path: /doorkomststaat/
  methods: [GET]
  controller: App\Controller\TrainTableController:passingRoutesAction
passing_routes_search:
  path: /doorkomststaat/{trainTableIndexNumber}/{locationName}/{dayNumber}/{startTime}/{endTime}/
  methods: [GET]
  requirements: { trainTableIndexNumber: \d+, dayNumber: \d+ }
  controller: App\Controller\TrainTableController:passingRoutesAction
special_routes:
  path: /drgl/
  methods: [GET]
  controller: App\Controller\TrainTableController:specialRoutesAction
special_route:
  path: /drgl/{id}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\TrainTableController:specialRoutesAction

#########
# Spots #
#########
spot_input:
  path: /invoer/
  methods: [GET, POST]
  controller: App\Controller\SpotInputController::indexAction
spot_input_feedback:
  path: /invoer-feedback/{idList}
  methods: [GET]
  requirements: { idList: .+ }
  controller: App\Controller\SpotInputController::feedbackAction
spots:
  path: /spots/
  controller: App\Controller\SpotController::indexAction
spots_search:
  path: /spots/{maxYears}/{searchParameters}
  methods: [GET]
  requirements: { maxYears: '1|2|3|4|5', searchParameters: .+ }
  controller: App\Controller\SpotController:indexAction
spots_to_train_table:
  path: /spots/naar-dienstregeling/{routeNumber}/{date}/
  methods: [GET]
  controller: App\Controller\SpotController:redirectToTrainTableAction
my_spots:
  path: /mijn-spots/
  controller: App\Controller\HomeController::homeAction
pois:
  path: /spotpunten/
  controller: App\Controller\HomeController::homeAction

##########
# Trains #
##########
train_compositions:
  path: /matsms/
  controller: App\Controller\HomeController::homeAction
ddar_trains:
  path: /ddar/
  controller: App\Controller\HomeController::homeAction

#########
# Forum #
#########
forum:
  path: /forum/
  methods: [GET]
  controller: App\Controller\ForumForumController:indexAction
forum_forum:
  path: /forum/c{id}/{name}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\ForumForumController:forumAction
forum_forum_new_discussion:
  path: /forum/n{id}/nieuwe-discussie/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ForumDiscussionController:newAction
forum_discussion:
  path: /forum/{id}/{name}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\ForumDiscussionController:indexAction
forum_discussion_page:
  path: /forum/{id}/{pageNumber}/{name}/
  methods: [GET]
  requirements: { id: \d+, pageNumber: \d+ }
  controller: App\Controller\ForumDiscussionController:indexAction
forum_discussion_post:
  path: /forum/{id}/p{postId}/{name}/
  methods: [GET]
  requirements: { id: \d+, postId: \d+ }
  controller: App\Controller\ForumDiscussionController:indexAction

forum_discussion_moderate:
  path: /forum/{id}/moderate/{action}/
  methods: [GET, POST]
  requirements: { id: \d+, action: 'close|open|move' }
  controller: App\Controller\ForumModerateController:indexAction
forum_discussion_moderate_combine:
  path: /forum/{id1}/moderate/combine/{id2}/
  methods: [GET, POST]
  requirements: { id1: \d+, id2: \d+ }
  controller: App\Controller\ForumModerateController:combineAction
forum_discussion_moderate_split:
  path: /forum/{id}/moderate/split/{postIds}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ForumModerateController:splitAction

forum_discussion_post_reply:
  path: /forum/p{id}/reageren/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ForumPostController:replyAction
forum_discussion_post_edit:
  path: /forum/p{id}/bewerken/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ForumPostController:editAction

forum_discussion_post_alert:
  path: /forum/p{id}/melden/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ForumPostAlertController:alertAction
forum_discussion_post_alerts_overview:
  path: /forum/meldingen/
  methods: [GET]
  controller: App\Controller\ForumPostAlertController:alertsAction
forum_discussion_post_alerts:
  path: /forum/p{id}/meldingen/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ForumPostAlertController:postAlertsAction
forum_discussion_post_alerts_close:
  path: /forum/p{id}/meldingen-sluiten/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\ForumPostAlertController:alertsCloseAction

forum_search:
  path: /forum/zoeken/
  methods: [GET]
  controller: App\Controller\ForumController:searchAction
forum_unread:
  path: /forum/ongelezen/
  methods: [GET]
  controller: App\Controller\ForumController:unreadAction
forum_mark_read:
  path: /forum/markeer-als-gelezen/
  methods: [GET]
  controller: App\Controller\ForumController:markAsReadAction

#########
# Somda #
#########
about:
  path: /over/
  methods: [GET]
  controller: App\Controller\SomdaController:aboutAction
advertise:
  path: /adverteren/
  methods: [GET]
  controller: App\Controller\SomdaController:advertiseAction
contact:
  path: /feedback/
  methods: [GET, POST]
  controller: App\Controller\SomdaController:contactAction
disclaimer:
  path: /disclaimer/
  methods: [GET]
  controller: App\Controller\SomdaController:disclaimerAction
disclaimer_choice:
  path: /disclaimer/{choice}/
  methods: [GET]
  controller: App\Controller\SomdaController:disclaimerAction
statistics:
  path: /statistieken/
  controller: App\Controller\HomeController::homeAction
help:
  path: /help/
  controller: App\Controller\HomeController::homeAction
help_text:
  path: /help/{id}/
  controller: App\Controller\HomeController::homeAction

########
# User #
########
settings:
  path: /instellingen/
  controller: App\Controller\SettingsController:indexAction
profile:
  path: /profiel/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ProfileController:indexAction
profile_view:
  path: /profiel/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ProfileController:indexAction
profile_mail:
  path: /profiel/e-mail/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ProfileController:mailAction

##############
# Management #
##############
manage_user:
  path: /beheer-gebruikers/
  controller: App\Controller\HomeController::homeAction

manage_news:
  path: /beheer-nieuws/
  controller: App\Controller\ManageNewsController::indexAction
manage_news_edit:
  path: /beheer-nieuws-item/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ManageNewsController::editAction

manage_rail_news:
  path: /beheer-spoor-nieuws/
  controller: App\Controller\ManageNewsController::indexAction
manage_rail_news_edit:
  path: /beheer-spoor-nieuws-item/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ManageNewsController::railNewsEditAction

manage_special_routes:
  path: /beheer-bijzonder-ritten/
  controller: App\Controller\ManageSpecialRoutesController::indexAction
manage_special_route:
  path: /beheer-bijzondere-rit/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ManageSpecialRoutesController::editAction

manage_banners:
  path: /beheer-banners/
  controller: App\Controller\HomeController::homeAction

manage_train_tables:
  path: /beheer-dienstregelingen/
  controller: App\Controller\ManageTrainTablesController::manageAction
manage_train_tables_year:
  path: /beheer-dienstregelingen-invoer/{yearId}/
  methods: [GET]
  requirements: { yearId: \d+ }
  controller: App\Controller\ManageTrainTablesController::manageAction
manage_train_tables_year_route_list:
  path: /beheer-dienstregelingen-invoer/{yearId}/{routeListId}/
  methods: [GET]
  requirements: { yearId: \d+, routeListId: \d+ }
  controller: App\Controller\ManageTrainTablesController::manageAction
manage_train_table:
  path: /beheer-dienstregeling/{routeListId}/{routeId}/
  methods: [GET, POST]
  requirements: { routeListId: \d+, routeId: \d+ }
  controller: App\Controller\ManageTrainTablesController::manageRouteAction

manage_pois:
  path: /beheer-spotpunten/
  controller: App\Controller\HomeController::homeAction

manage_bans:
  path: /beheer-bans/
  controller: App\Controller\ManageUsersController::bansAction
manage_ban:
  path: /beheer-ban/{id}/
  methods: [GET, POST]
  requirements: { id: \d+ }
  controller: App\Controller\ManageUsersController::banAction

manage_ddar_trains:
  path: /beheer-ddar/
  controller: App\Controller\HomeController::homeAction

manage_train_compositions:
  path: /beheer-materieel-samenstellingen/
  controller: App\Controller\HomeController::homeAction

manage_route_lists:
  path: /beheer-treinnummerlijst/
  methods: [GET]
  controller: App\Controller\ManageRouteListsController::routeListsAction
manage_route_lists_year:
  path: /beheer-treinnummerlijst/{id}/
  methods: [GET]
  requirements: { id: \d+ }
  controller: App\Controller\ManageRouteListsController::routeListsAction
manage_route_list:
  path: /beheer-treinnummerlijst-item/{yearId}/{id}/
  methods: [GET, POST]
  requirements: { yearId: \d+, id: \d+ }
  controller: App\Controller\ManageRouteListsController::routeListAction



gespotmat:
  path: /
  controller: App\Controller\HomeController::homeAction
ongelezen:
  path: /
  controller: App\Controller\HomeController::homeAction
reisplanner:
  path: /
  controller: App\Controller\HomeController::homeAction
ongelezen_forum:
  path: /
  controller: App\Controller\HomeController::homeAction
spoornieuws:
  path: /
  controller: App\Controller\HomeController::homeAction
materieelnamen:
  path: /
  controller: App\Controller\HomeController::homeAction
favorieten:
  path: /
  controller: App\Controller\HomeController::homeAction
feeds:
  path: /
  controller: App\Controller\HomeController::homeAction
forum/zoeken:
  path: /
  controller: App\Controller\HomeController::homeAction
shout_archief:
  path: /
  controller: App\Controller\HomeController::homeAction
grafisch:
  path: /
  controller: App\Controller\HomeController::homeAction
