parameters:
  router.request_context.scheme: 'https'
  asset.request_context.secure: true

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
  debril.rss_atom.provider:
    class: App\Feed\FeedProvider
