openapi: 3.0.0
info:
  title: 'Swagger Petstore'
  description: 'A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: 'Swagger API Team'
  license:
    name: MIT
  version: 1.0.0
servers:
  -
    url: petstore.swagger.io
    description: 'API server'
paths: ~
components:
  schemas:
    NewForumPost:
      required:
        - signatureOn
        - text
      properties:
        signatureOn:
          type: integer
          enum: [0, 1]
        text:
          type: string
      type: object
